### ISSUE TITLE
代码啦下来 HBuilder 里直接运行报错

### ISSUE THREAD

**Issue by hst-Sunday** [cool-team-official/cool-uni#38]
代码啦下来 HBuilder 里直接运行报错
<img width="611" alt="image" src="https://github.com/cool-team-official/cool-uni/assets/18478530/a53be098-92b6-4bac-a723-24680ac76041">

**Comment by hst-Sunday** [comment]
回退到11月3号的提交没问题  估计是依赖包有问题

**Comment by hst-Sunday** [comment]
获取eps数据后会报这个错

**Comment by hst-Sunday** [comment]
要匹配后端的11月7号的版本

**Comment by icssoa** [comment]
> 要匹配后端的11月7号的版本

已修复
